name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - dev

jobs:
  build_front:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub Registry
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build Docker Image
      run: docker build -t overflooow/waypoint-front:${{ github.ref == 'refs/heads/main' && 'latest' || 'dev' }} .
  
    - name: Push Docker Image
      run: docker push overflooow/waypoint-front:${{ github.ref == 'refs/heads/main' && 'latest' || 'dev' }} 
